### ISSUE TITLE
Can't launch current version

### ISSUE THREAD

**Issue by harrysargent** [MarkHopper24/barcodrod.io#20] opened 2024-01-08 15:53 UTC
Long time (and very grateful) user of this top-tier app. Re latest version - can install but not open app on new laptop - tried installing from all available sources (except self-build) and built-in modern app repair/reset options. **Previous versions incl v1.7 install and run as expected** when installed via GitHub msix packages.
 
barcodrod.io v1.8
Windows 11 Home x64 Build 22631
i7-1260P

**Comment by MarkHopper24** [comment] 2024-01-08 16:07
Thanks for reporting this issue @harrysargent. Will begin investigating this evening. I may ask for more information as I hadn't come across any crashes on start up in my testing, will keep you posted.

**Comment by mejsler** [comment] 2024-01-16 14:46
same issue

**Comment by naillamarb** [comment] 2024-01-16 21:35
Installed v1.8 OS Edition, Microsoft Windows 10 Pro x64OS Version, 22H2 OS Build, 19045.3930, Not able to get it to launch.

**Comment by MarkHopper24** [comment] 2024-01-19 13:16
Ack @mejsler @naillamarb, thanks for the +1's. I haven't been able to reproduce this yet, but I'm still investigating and will ship a few changes that may fix (or at the very least help diagnose) this issue in a patch hopefully in the next week or so.

In the meantime, can you let me know if the app was installed directly from the MSIX on GitHub or the Microsoft Store? Also, can you check the following path to see if the settings.json file exists? 

_%localappdata%\packages\53383MarkHopper.570136E6C1E54_25krmwkbgncsa\LocalState\settings.json_


 If it doesn't, please try to create the file manually with this content:
 `{
  "UserModified": false,
  "HistoryEnabled": true,
  "BackdropIndex": 0
}`

...and try to launch again. If the issue is what I suspect, this may be a workaround to use 1.8 before I ship the next update. Thanks again.

**Comment by MarkHopper24** [comment] 2024-01-21 19:51
I just submitted v1.8.1 to the Microsoft Store which includes a few potential fixes for this issue + basic logging support. It should be available within the next few days.

If the crash is not resolved once v1.8.1 is available, please send me the log file located at:

_%localappdata%\packages\53383MarkHopper.570136E6C1E54_25krmwkbgncsa\LocalState\log.txt_

**Comment by harrysargent** [comment] 2024-01-21 20:02
The settings.json workaround fixes 1.8 for me; I'll keep an eye out for the 1.8.1 update and feed back when it arrives

**Comment by MarkHopper24** [comment] 2024-01-21 20:21
@harrysargent Appreciate you testing that out. The workaround fixing the crash is a very promising indicator that the v.1.8.1 changes should properly address this issue. Will leave this open for folks to validate once released. Thanks again.

**Comment by MarkHopper24** [comment] 2024-01-22 17:46
@harrysargent @naillamarb @mejsler v1.8.1 is now available on the Microsoft Store & GitHub and should address this issue. 
https://github.com/MarkHopper24/barcodrod.io/releases/tag/v1.8.1

Please let me know if you are still encountering startup crashes after updating, otherwise will close this one out later today. 
Thanks!

**Comment by harrysargent** [comment] 2024-01-22 18:01
1.8.1 fixes the bug, both as an update and as a fresh install. Thanks Mark!

**Closed as completed** 2024-01-22 18:23 UTC
Labels: bug, fix incoming
